### ISSUE TITLE
Your App needs an App abstraction.

### ISSUE THREAD

**Issue by josmardias** [tgfoundation/formula#5]
The `index.js` file should be just an entry point, that NPM/Node requires by default.
`index.js`  has just one purpose: to render your App, maybe with needed params.
It's not a React pattern, it's a life pattern.

Maybe you'll find it over engineering, and probably it is in this case. But it's really easy to do, and has lot of potencial to make testing easier and help you think reason about your application bounds.

For example, if your application renders as CLI, `index.js` can handle params passed as argument (`./index.js <param1> <param2>`) and your application can just receive those params as argument.
This way you can remove part of the complexity from your application, it's great for testing (it's ok to not test the trivial part of passing param to the executable).
Do your application care about how those starting params are received, like CLI arguments or other application rendering you? Probably not.

So, you need to create an `<App />` component, do your stuff inside it, and render the App inside `index.js`

**Comment by josmardias** [comment]
Your `index.js` will probably be something like thise:
```
import React from 'react'
import ReactDOM from 'react-dom'

import App from './App'

const rootNode = document.getElementById('root')

ReactDOM.render(
  <App />,
  rootNode,
)
```

**Comment by tgfassina** [comment]
Thanks. Fix incoming.
