### ISSUE TITLE
CSS can be imported on JavaScript (and it's ok)

### ISSUE THREAD

**Issue by josmardias** [tgfoundation/formula#6]
avoid this pattern on `index.html`
```
        <link rel="stylesheet" href="custom.css">
        <link rel="stylesheet" href="formula.css">
```

Using `formula.css` as example:

* move `formula.css` to `/src`
* add this to `formula.jsx`:
```
import React from 'react';
import 'formula.css'
```

**Comment by josmardias** [comment]
Why this other pattern is better?

1) Webpack will bundle css with JavaScript, and it's the only way you can make sure your components are bundled as single pieces. If you use advanced `webpack` features, for example code split, you can make sure user downloads assets (js, css, images...) only when needed, instead of the whole application at first boot. It's only possible if you use webpack feature of css importing.

2) It's easier to reason about you UI components when all pieces of a given component is in the same folder. For example, you can create `src/ui` and inside it put `formula.js`, `formula.css`, `formula.story.js` (if you use Storybook), and `formula.test.js` (if you perform ui components testing). A lot better than spreading shit accross the universe.

**Comment by tgfassina** [comment]
Cool. Worked just fine. Additionally, is there anything I can do about the other things I have included on the layout? (font-awesome and bootstrap [css, js, tether, jquery]). Those are included from CDN's, but perhaps there is a way of specifying on my `package.json` or something.

**Comment by josmardias** [comment]
Yes, there is a better way to do using `npm install` and `import`
I'll try a PR for this one if you don't mind
