### ISSUE TITLE
Do not name files .jsx

### ISSUE THREAD

**Issue by josmardias** [tgfoundation/formula#7]
JSX is just a sintax sugar. It's compiled to plain old JavaScript to run on browser, the same as `import`, that is not supported by browsers right now.

Name than just `.js`, because JavaScript they are.

**Comment by josmardias** [comment]
For example:

```
const Formula = () => (
  <div className="row">
    <div className="col">
      <h1>Write formula</h1>
      <FormulaInput />
      <FormulaPreview />
    </div>
  </div>
)
```

compiles to 
```
var Formula = function Formula() {
  return React.createElement(
    "div",
    { className: "row" },
    React.createElement(
      "div",
      { className: "col" },
      React.createElement(
        "h1",
        null,
        "Write formula"
      ),
      React.createElement(FormulaInput, null),
      React.createElement(FormulaPreview, null)
    )
  );
};
```

**Comment by josmardias** [comment]
Then you say:
```
But ECMA2015 will be supported one day. JSX will never be native browser feature
```

Who cares? React community invented this pattern, not you. They deeply regrets it and do not use it anymore. If they used just `.js` in the first place, will you create `.jsx` extension?
It's tottaly useless to warn developer that a files uses JSX on a React project.

It's just like naming your variables strName. It's useless, because name is probably a string.
Just give good names to your files and good luck.

**Comment by tgfassina** [comment]
Fix incoming.
