### ISSUE TITLE
Do not early bind you methods

### ISSUE THREAD

**Issue by josmardias** [tgfoundation/formula#8]
```
        super();
        this.addParameter = this.addParameter.bind(this);
        this.updateValue = this.updateValue.bind(this);
```
It's the worse pattern I ever found doing React

Look at Bernardo's case. He did that, and some weeks later he did not know why passing methods  sometimes worked, sometimes not. It's terrible for new coworkers as well.

Do the binding as needed, while passing parameters ahead. It's easy to understand just as easy to understand all those binds on `constructor()`, probably easier, because it's explicit.

**Comment by tgfassina** [comment]
What you said makes sense, but I'll keep this for a little while longer until I feel more confident about the bindings and until the code grows a bit and I feel the necessity.
